{"name": "Авторизаиця с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1744168607142, "stop": 1744168610267}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1744168610267, "stop": 1744168610352}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1744168610352, "stop": 1744168610361}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1744168607142, "stop": 1744168610361, "uuid": "44422dd5-0bc0-4d71-b440-fee0f2be5b08", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "feature", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "WIN-T13NHRIR3JH"}, {"name": "thread", "value": "17620-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}