{"name": "Авторизаиця с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1744167992485, "stop": 1744167996329}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1744167996329, "stop": 1744167996478}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1744167996478, "stop": 1744167996487}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1744167992485, "stop": 1744167996487, "uuid": "c1359017-9553-469b-9afd-db57eb8f2214", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "feature", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "WIN-T13NHRIR3JH"}, {"name": "thread", "value": "21464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}